id: I2E12275A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T18:22:41+00:00'
last_modified: '2022-06-08T06:43:54.706623+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23993
  title: ཕྱག་རྒྱ་ཆེན་པོ་བརྡའི་སྐོར་གསུམ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    8B49:
      image_group_id: I3605
      title: ''
      total_pages: 300
      order: 1
      base_file: 8B49.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
