id: P006769
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:21:59.013172
source_metadata:
  id: bdr:W23993
  title: ཕྱག་རྒྱ་ཆེན་པོ་བརྡའི་སྐོར་གསུམ
  author: ''
  volumes:
    0eb6b7dfaf2046d3bbaefca940430b72:
      image_group_id: I3605
      title: ''
      volume_number: 1
      total_pages: 300
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
